"""Sprint 6 BL-0069: AI 出力直結禁止 lint (AI Output Boundary §1 強制).

artifact graph で source=ai output が次の sinks に直接つながる edge を
fail-closed で reject:

- shell command 実行
- SQL 実行
- migration apply (Alembic 実行)
- ``.github/workflows/**`` 書込み
- 外部 mutating tool 呼出 (MCP write 系)
- repository patch 適用 (commit / push)

設計 (DD-04 + AI Output Boundary §1):

- artifact graph は ``ArtifactGraph`` (node = artifact, edge = transformation)
  として渡される。本 module は graph を **静的解析** し、source=ai
  artifact から allow-list 外の sink へ edge があれば violation を返す。
- ``ArtifactNode.kind`` で artifact 種別を区別 (`plan` / `patch` / `cli_*`
  / `evidence` / `command` / `sql` / `migration` / `workflow` / `external_tool`
  / `repo_patch_applied`)。
- ``source=ai`` は AI 出力 (e.g. cli_stdout / plan generated by AI) を表す
  ``ArtifactNode.source`` field。
- approval / policy_lint / runner_gate を経た artifact は ``source=trusted``
  に昇格できる (Sprint 5.5 Input Trust Layer の Approval 4 整合 hash binding
  を通過した場合)。
- ``runner_completed`` event を経て生成された artifact は ``source=runner``
  となり、runner_mutation_gateway 通過の証拠を持つ。

server-owned-boundary §1 不変条件:

- ``ArtifactNode.source`` / ``kind`` は caller-supplied だが、本 module は
  **policy enforcement (validation only)** であり mutation はしない。
  実際の artifact 生成は別 module で server 側が source を決定する。
- 違反検出時は ``DirectExecutionViolation`` を返し、caller が
  ``AgentRun.status = blocked + runtime_blocked`` に遷移させる responsibility
  を持つ。
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Literal


class ArtifactSource(StrEnum):
    AI = "ai"  # AI 出力 (provider response / CLI stdout など)
    CLI_LAUNCHER = "cli_launcher"  # CLI launcher subprocess output
    TRUSTED = "trusted"  # Approval 4 整合通過後の昇格済 artifact
    RUNNER = "runner"  # runner_mutation_gateway 通過後の artifact
    HUMAN = "human"  # human が直接入力


class ArtifactKind(StrEnum):
    PLAN = "plan"
    PATCH = "patch"
    EVIDENCE = "evidence"
    CITATION = "citation"
    CLI_INPUT = "cli_input"
    CLI_STDOUT = "cli_stdout"
    CLI_STDERR = "cli_stderr"
    CLI_EXIT = "cli_exit"
    CLI_RESULT_SUMMARY = "cli_result_summary"
    # Sink kinds (mutation を引き起こす)
    SHELL_COMMAND = "shell_command"
    SQL_STATEMENT = "sql_statement"
    MIGRATION = "migration"
    WORKFLOW_FILE = "workflow_file"  # .github/workflows/**
    EXTERNAL_TOOL_CALL = "external_tool_call"
    REPO_PATCH_APPLIED = "repo_patch_applied"


# AI Output Boundary §1: ``source=ai`` から **直接** 接続が禁止される sink。
# trusted / runner / human source 経由なら許可 (Approval / runner gate 通過済)。
_FORBIDDEN_AI_TO_SINK: frozenset[ArtifactKind] = frozenset({
    ArtifactKind.SHELL_COMMAND,
    ArtifactKind.SQL_STATEMENT,
    ArtifactKind.MIGRATION,
    ArtifactKind.WORKFLOW_FILE,
    ArtifactKind.EXTERNAL_TOOL_CALL,
    ArtifactKind.REPO_PATCH_APPLIED,
})

# cli_launcher source (subprocess output) も AI 出力扱い (CLI = AI agent)
_AI_LIKE_SOURCES: frozenset[ArtifactSource] = frozenset({
    ArtifactSource.AI,
    ArtifactSource.CLI_LAUNCHER,
})


@dataclass(frozen=True, slots=True)
class ArtifactNode:
    artifact_id: str
    source: ArtifactSource
    kind: ArtifactKind


@dataclass(frozen=True, slots=True)
class ArtifactEdge:
    """transformation edge (parent_artifact → child_artifact)."""

    parent_artifact_id: str
    child_artifact_id: str


@dataclass(frozen=True, slots=True)
class DirectExecutionViolation:
    parent_artifact_id: str
    parent_source: ArtifactSource | None  # None when graph integrity violated
    child_artifact_id: str
    child_kind: ArtifactKind | None  # None when graph integrity violated
    reason: Literal[
        "ai_source_to_forbidden_sink",
        "graph_integrity_unknown_node",
    ]


@dataclass(frozen=True, slots=True)
class LintResult:
    violations: tuple[DirectExecutionViolation, ...]

    @property
    def is_clean(self) -> bool:
        return len(self.violations) == 0


def lint_artifact_graph(
    *,
    nodes: tuple[ArtifactNode, ...],
    edges: tuple[ArtifactEdge, ...],
) -> LintResult:
    """artifact graph を静的解析し、AI Output Boundary §1 違反 edge を返す。

    Args:
        nodes: artifact node の全リスト。同 artifact_id が複数存在しても
            最初の出現を採用 (defensive)。
        edges: parent→child の transformation edge。

    Returns:
        ``LintResult`` (violations が空なら ``is_clean=True``)。
    """

    by_id: dict[str, ArtifactNode] = {}
    for node in nodes:
        by_id.setdefault(node.artifact_id, node)

    violations: list[DirectExecutionViolation] = []
    for edge in edges:
        parent = by_id.get(edge.parent_artifact_id)
        child = by_id.get(edge.child_artifact_id)
        # Codex SP6B3 R1 F-004 (HIGH) adopt: graph 欠損 edge は **silent
        # skip しない**。AI output -> forbidden sink の detect 漏れを物理削除
        # するため、未知 node を持つ edge は graph integrity violation として
        # 返す (fail-closed)。
        if parent is None or child is None:
            violations.append(
                DirectExecutionViolation(
                    parent_artifact_id=edge.parent_artifact_id,
                    parent_source=parent.source if parent is not None else None,
                    child_artifact_id=edge.child_artifact_id,
                    child_kind=child.kind if child is not None else None,
                    reason="graph_integrity_unknown_node",
                )
            )
            continue
        if (
            parent.source in _AI_LIKE_SOURCES
            and child.kind in _FORBIDDEN_AI_TO_SINK
        ):
            violations.append(
                DirectExecutionViolation(
                    parent_artifact_id=parent.artifact_id,
                    parent_source=parent.source,
                    child_artifact_id=child.artifact_id,
                    child_kind=child.kind,
                    reason="ai_source_to_forbidden_sink",
                )
            )
    return LintResult(violations=tuple(violations))


__all__ = [
    "ArtifactEdge",
    "ArtifactKind",
    "ArtifactNode",
    "ArtifactSource",
    "DirectExecutionViolation",
    "LintResult",
    "lint_artifact_graph",
]
