from __future__ import annotations

from typing import Literal

AgentRunEventType = Literal[
    "run_queued",
    "context_gathered",
    "provider_requested",
    "provider_responded",
    "artifact_generated",
    "schema_validated",
    "validation_failed",
    "repair_retry_scheduled",
    "policy_linted",
    "policy_blocked",
    "budget_blocked",
    "runtime_blocked",
    "diff_ready",
    "approval_requested",
    "approval_decided",
    "runner_started",
    "runner_completed",
    "runner_blocked",
    "repo_pr_opened",
    "run_completed",
    "run_failed",
    "run_cancelled",
    "repair_exhausted",
    "trust_level_promoted",
    "trust_level_promotion_denied",
    "cli_invocation_started",
    "cli_process_completed",
    "cli_decision_recorded",
    "orchestrator_dispatched",
    "orchestrator_lease_renewed",
    "orchestrator_lease_expired",
    "orchestrator_failover_triggered",
    "orchestrator_kill_engaged",
    "inter_agent_message_sent_ref",
    "inter_agent_message_consumed_ref",
    "tool_web_fetch_executed",
    "tool_docs_search_executed",
    # SP-PHASE1 B1 (ADR-00048 §Amendment A-5, user 承認 2026-06-22): emergency-stop
    # block / resume の dedicated witnessing event。汎用 event 再利用は audit semantic
    # を不正確化する (repair_exhausted 前例) ため専用 event_type を 2 つ追加。P0 event
    # として追加 (P0.1 sealed extension 29-37 とは別位置、sealed guard に抵触しない)。
    "emergency_stop_engaged",
    "emergency_stop_resumed",
]

ALL_AGENT_RUN_EVENT_TYPES: tuple[AgentRunEventType, ...] = (
    "run_queued",
    "context_gathered",
    "provider_requested",
    "provider_responded",
    "artifact_generated",
    "schema_validated",
    "validation_failed",
    "repair_retry_scheduled",
    "policy_linted",
    "policy_blocked",
    "budget_blocked",
    "runtime_blocked",
    "diff_ready",
    "approval_requested",
    "approval_decided",
    "runner_started",
    "runner_completed",
    "runner_blocked",
    "repo_pr_opened",
    "run_completed",
    "run_failed",
    "run_cancelled",
    "repair_exhausted",
    "trust_level_promoted",
    "trust_level_promotion_denied",
    "cli_invocation_started",
    "cli_process_completed",
    "cli_decision_recorded",
    "orchestrator_dispatched",
    "orchestrator_lease_renewed",
    "orchestrator_lease_expired",
    "orchestrator_failover_triggered",
    "orchestrator_kill_engaged",
    "inter_agent_message_sent_ref",
    "inter_agent_message_consumed_ref",
    "tool_web_fetch_executed",
    "tool_docs_search_executed",
    "emergency_stop_engaged",
    "emergency_stop_resumed",
)

__all__ = ["ALL_AGENT_RUN_EVENT_TYPES", "AgentRunEventType"]

